### PR TITLE
Added support for 'globallycoherent' keyword

### LINKED ISSUE #54: Missing keyword: globallycoherent
Example usage:
`globallycoherent RWBuffer<uint> BoundingBox : register(u2);`

Error:
unexpected token globallycoherent

### PR DESCRIPTION
**Pull request by OndrejPetrzilka**
This was simple. `ShaderTools.Hlsl.Syntax.StorageFlags` is not used, should it be removed? Fixes #54

### CODE REVIEW

**Comment by tgjones** [comment]
I have fixed the `OutliningTagger` issue (967c185920923ad59fc9b056ca3dc5126beae851) so feel free to remove your workaround :)

**Comment by tgjones** [comment]
Yes, please do remove `StorageFlags`. At some point it would be nice to expose that information through the `Symbol` hierarchy, but it's very low priority, so let's remove it for now.

**Comment by tgjones** [comment]
Thanks! Is this ready to merge?

**Comment by OndrejPetrzilka** [comment]
Yes, it's ready

**Pull request merged**
